# Generated by Django 4.1.1 on 2022-09-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=None, max_length=16, null=True, verbose_name='Дата выполнения'),
        ),
    ]
